### ISSUE TITLE
When application crashes, ipdb also crashes saying: name 'Restart' is not defined

### ISSUE THREAD

**Issue by Chiel92** [gotcha/ipdb#83] opened 2016-02-23 09:00 UTC
I'm trying to switch from `pdb` to `ipdb`, and in order to do that I installed the following packages with pip 3.
```
Python 3.5.0
ipython 4.1.1
ipdb-0.9.0
pyreadline-2.1
```

The command I run `ipdb` with is `python3 -m ipdb runtest.py`, where `runtest.py` is a script in which an exception occurs.

This is the full stack trace:

```
C:\Program Files\Python 3.5\lib\site-packages\ipdb\__main__.py:113: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'context' in getargspec(Pdb.__init__)[0]:
ipdb> c
Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\site-packages\ipdb\__main__.py", line 196, in main
    pdb._runscript(mainpyfile)
  File "C:\Program Files\Python 3.5\lib\pdb.py", line 1542, in _runscript
    self.run(statement)
  File "C:\Program Files\Python 3.5\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>

<My Application Stack Trace Here>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python 3.5\lib\site-packages\ipdb\__main__.py", line 217, in <module>
    main()
  File "C:\Program Files\Python 3.5\lib\site-packages\ipdb\__main__.py", line 200, in main
    except Restart:
NameError: name 'Restart' is not defined

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Is this is a ipdb bug?

**Comment by gotcha** [comment] 2016-02-23 10:29
This seems related to https://github.com/gotcha/ipdb/issues/55.

**Comment by fvisin** [comment] 2016-03-02 19:26
I am experiencing the same problem:
>   Traceback (most recent call last):
>   File "/u/visin/.miniconda/envs/arctic/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/u/visin/.miniconda/envs/arctic/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/u/visin/.miniconda/envs/arctic/lib/python2.7/site-packages/ipdb/__main__.py", line 217, in <module>
>     main()
>   File "/u/visin/.miniconda/envs/arctic/lib/python2.7/site-packages/ipdb/__main__.py", line 200, in main
>     except Restart:
> NameError: global name 'Restart' is not defined
>

**Comment by fvisin** [comment] 2016-03-03 00:09
As a workaround, reverting to ipdb-0.8.1 and ipython-4.1.1 solves the problem.

**Comment by fvisin** [comment] 2016-04-28 19:36
Is there any improvement on this issue? I still experience the same problem with ipython (4.2.0) and ipdb (0.9.3) whenever I run `python -m ipdb somefile.py` as soon as I hit `c` (continue). This is very annoying as it prevents me to use ipdb to debug. I am available to do some tests if needed, let me know if you have any pointer.

**Comment by gotcha** [comment] 2016-04-29 10:04
@fvisin Is this happening only with Python 3.5 ?
I cannot reproduce with 3.4.

**Comment by gotcha** [comment] 2016-04-29 10:27
@fvisin can you try fix in https://github.com/gotcha/ipdb/tree/fix_restart ?

**Comment by fvisin** [comment] 2016-04-29 14:39
@gotcha it works! Thanks for the fix!!

**Comment by gotcha** [comment] 2016-04-29 15:59
Released as https://pypi.python.org/pypi/ipdb/0.9.4

**Closed by gotcha** 2016-04-29 15:59 UTC
