### ISSUE TITLE
IPDB usability issues

### ISSUE THREAD

**Issue by mindojo-victor** [gotcha/ipdb#90] opened 2016-04-01 04:32 UTC
I suspect these issues were covered somewhere, but it's a pity they are still present. `ipdb` servers well, I would like to not look for other debuggers. I also suspect some of them are caused by ipython, but I don't know the internals and I think ipdb is the deliverer.

``` python
ipdb> list()
*** Error in argument: '()'
ipdb> Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3115, in atexit_operations
    self.history_manager.end_session()
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 504, in end_session
    self.writeout_cache()
  File "<string>", line 2, in writeout_cache
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 65, in needs_sqlite
    return f(self, *a, **kw)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 680, in writeout_cache
    self._writeout_input_cache(conn)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 664, in _writeout_input_cache
    (self.session_number,)+line)
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145306509312 and this is thread id 140735133020160
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3115, in atexit_operations
    self.history_manager.end_session()
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 504, in end_session
    self.writeout_cache()
  File "<string>", line 2, in writeout_cache
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 65, in needs_sqlite
    return f(self, *a, **kw)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 680, in writeout_cache
    self._writeout_input_cache(conn)
  File "/Users/Vic/projects/brain/venv/lib/python2.7/site-packages/IPython/core/history.py", line 664, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145306509312 and this is thread id 140735133020160
Validating models...

0 errors found
Django version 1.3.3, using settings 'temproj.settings'
Development server is running at http://127.0.0.1:8001/
Quit the server with CONTROL-C.
```
1. Built-in functions and local variables are shadowed by ipdb commands.
2. If the Django server is restarted because of code changes: annoying `sqlite3.ProgrammingError`.
3. And the commands are not saved in history, if I press Ctrl+D or Ctrl+\ or Ctrl+C.

**Comment by gotcha** [comment] 2016-04-12 12:53
Which version of `ipdb` are you using ?

**Comment by mindojo-victor** [comment] 2016-04-12 16:18
`ipdb==0.9.0`

**Comment by gnebehay** [comment] 2017-01-21 21:22
1) can be solved by using `!list`
2) Seems to be an IPython issue
3) Duplicate of #59

**Closed by gnebehay** 2017-01-21 21:22 UTC
Labels: Duplicate

**Comment by mindojo-victor** [comment] 2017-01-21 21:59
> can be solved by using `!list`

This is annoying

**Comment by gnebehay** [comment] 2017-01-21 22:16
It may be annoying for you, but it is a design decision that has its roots in pdb: https://docs.python.org/3/library/pdb.html . In the end you need some way of escaping python variable names and `!` just happens to do that. Of course you could have it the other way round and you would escape all debugging commands whenever you have conflicts with python keywords/variables, but then the other half of the population would complain.

One way or the other, this is nothing that we can change for you, as this stuff is buried in the IPython debugger, which does the actual work.
