### ISSUE TITLE
Unable to set variables inside the ipdb console

### ISSUE THREAD

**Issue by alichaudry** [gotcha/ipdb#121] opened 2016-12-02 22:54 UTC
For example:

```
In [1]: def do_something():
   ...:     var1 = 123
   ...:     var2 = 908
   ...:     var3 = 241
   ...:     return var1 + var2 + var3
   ...:

In [2]: import ipdb

In [3]: ipdb.runcall(do_something)
> <ipython-input-1-7962c7547372>(2)do_something()
      1 def do_something():
----> 2     var1 = 123
      3     var2 = 908
      4     var3 = 241
      5     return var1 + var2 + var3

ipdb> n
> <ipython-input-1-7962c7547372>(3)do_something()
      1 def do_something():
      2     var1 = 123
----> 3     var2 = 908
      4     var3 = 241
      5     return var1 + var2 + var3

ipdb> var1
123
ipdb> var1 = 333
ipdb> var1
123
ipdb> q
```

Doing the same in `pdb` works just fine. I'm on `ipdb==0.10.1` and `Python 2.7.8`.

**Comment by gnebehay** [comment] 2017-01-20 12:33
IPython issue https://github.com/ipython/ipython/issues/9887
Duplicate of https://github.com/gotcha/ipdb/issues/107

**Comment by gnebehay** [comment] 2017-02-27 14:26
Fixed by upstream.

**Closed by gnebehay** 2017-02-27 14:26 UTC
Labels: Duplicate, IPython issue, Waiting for upstream fix
